import './globals.css'
import { Spline_Sans, Spline_Sans_Mono } from 'next/font/google'

const spline_sans_mono = Spline_Sans_Mono({
  weight: ['400', '700'],
  subsets: ['latin']
})

const spline_sans = Spline_Sans({
  weight: ['400', '600'],
  subsets: ['latin']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={spline_sans_mono.className}>
        {children}
      </body>
    </html>
  )
}
